---
title: "Estrelas Avantgarde"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: TRUE
toc-title: "Sumário"
---

# Rating

### Por Ativo

```{r, include=FALSE}
library(Rblpapi)
library(tidyverse)
library(lubridate)
library(DT)

con <- blpConnect()

source('functions.R')
```

```{r, include=FALSE}
comp_ibx <- get_index_comp('IBX Index', '2021-12-31', today(), 1)

comp_smll <- get_index_comp('SMLLBV Index', '2021-12-31', today(), 1)

sintetic_index <- merge_comp_indxs(list(comp_ibx, comp_smll), c(1, 1))
```

```{r, include=FALSE}
# Metrics that we will consider
fields_value <- c('PX_TO_BOOK_RATIO', 'PE_RATIO')
fields_size <- c('CUR_MKT_CAP')
fields_momentum <- c('HIST_TRR_PREV_2YR', 'EQY_TRR_PCT_1YR')
fields_low_vol <- c('EQY_BETA', 'VOLATILITY_260D')

fields_list <- list(fields_value, fields_size, fields_momentum, fields_low_vol)
names(fields_list) <- c('Value', 'Size', 'Momentum', 'Low Vol')

# Select the assets that we will work with
last_month <- colnames(sintetic_index)[ncol(sintetic_index)]

sintetic_index <- sintetic_index %>% 
  dplyr::select(c('Ticker', all_of(last_month))) %>% 
  dplyr::filter(!!as.symbol(last_month) != 0)

tickers <- sapply(sintetic_index$Ticker, function(x) paste(x, 'Equity'))

# Get the data for each factor
options <- structure(c("TRUE"), names = c("adjustmentSplit"))

metrics <- lapply(fields_list, function(x) bdp(tickers, x))
```

```{r, include=FALSE}
# Normalize every metric
metrics_norm <- lapply(metrics, function(x) apply(x, 2, function(y) (y - mean(y, na.rm = T)) / sd(y, na.rm = T)))

# Some factors are of the type buy low, sell high; for these metrics we need to change the sign
metrics_name <- c('PX_TO_BOOK_RATIO', 'PE_RATIO', 'CUR_MKT_CAP', 'EQY_BETA', 'VOLATILITY_260D')
metrics_norm_sign <- lapply(metrics_norm, function(x) change_sign(x, metrics_name))

# Finally, we take the average of each factor
metrics_final <- list()
for (i in seq_along(metrics_norm_sign)) {
  factor_metric <- metrics_norm_sign[[i]]
  
  sintetic_metric <- apply(factor_metric, 1, function(x) mean(x, na.rm = T))

  factor_metric <- data.frame(rownames(factor_metric), sintetic_metric)
  
  metrics_final[[i]] <- factor_metric
  
  colnames(metrics_final[[i]]) <- c('Ticker', names(fields_list)[i])
}

metrics_final <- Reduce(function(x, y) merge(x, y, all=TRUE), metrics_final)

```

```{r, include=FALSE}
# Now we order each factor and every asset with available data recieves a star
# 1 and 5 stars: 10 pct, 2 and 4 stars: 20 pct, 3 stars: 40 pct
stars_sys <- list()
for (i in 1:(ncol(metrics_final)-1)) {
  
  factor_name <- colnames(metrics_final)[i+1]
  
  factor_metric <- metrics_final[c('Ticker', factor_name)]
  
  factor_metric <- factor_metric %>% 
    arrange(desc(!!as.symbol(factor_name))) %>% 
    na.omit(.)
  
  stars <- get_stars_rating(factor_metric)
  
  stars <- data.frame(factor_metric$Ticker, stars)
  
  colnames(stars) <- c('Ticker', factor_name)
  
  stars_sys[[i]] <- stars
}

stars_sys <- Reduce(function(x, y) merge(x, y, all=TRUE), stars_sys)

# The general score is the average star across all factors
overall_score <- data.frame(stars_sys$Ticker, apply(stars_sys[,-1], 1, mean))

overall_score <- overall_score %>%
  set_names(c('Ticker', 'Overall')) %>% 
  arrange(desc(Overall)) %>% 
  na.omit(.)

overall_stars <- get_stars_rating(overall_score)

overall_stars <- data.frame(overall_score$Ticker, overall_stars)

colnames(overall_stars) <- c('Ticker', 'Overall')

stars_sys <- merge(stars_sys, overall_stars, all = TRUE)

```

```{r, echo = FALSE}
name_sector <- bdp(stars_sys$Ticker, c('Name', 'GICS_SECTOR_NAME'))
name_sector$Ticker <- rownames(name_sector)

stars_sys <- merge(name_sector, stars_sys, by = 'Ticker', all.y = TRUE)

stars_final <- stars_sys %>% 
  dplyr::select(!'GICS_SECTOR_NAME') %>% 
  mutate(across(!c(Name, Ticker), ~strrep('\xE2\xAD\x90', .x))) %>% 
  column_to_rownames(var = 'Name')
  

datatable(stars_final)
```

### Por Setor

```{r, echo = FALSE}
ranking_sector <- stars_sys %>%
  group_by(GICS_SECTOR_NAME) %>%
  summarise(Value = mean(Value, na.rm = TRUE), 
            Size = mean(Size, na.rm = TRUE), 
            Momentum = mean(Momentum, na.rm = TRUE),
            `Low Vol` = mean(`Low Vol`, na.rm = TRUE), 
            Overall = mean(Overall, na.rm = TRUE)) 
  
# Now we order each factor and every asset with available data recieves a star
# 1 and 5 stars: 10 pct, 2 and 4 stars: 20 pct, 3 stars: 40 pct
stars_sector <- list()
for (i in 1:(ncol(ranking_sector)-1)) {
  
  factor_name <- colnames(ranking_sector)[i+1]
  
  factor_metric <- ranking_sector[c('GICS_SECTOR_NAME', factor_name)]
  
  factor_metric <- factor_metric %>% 
    arrange(desc(!!as.symbol(factor_name))) %>% 
    na.omit(.)
  
  stars <- get_stars_rating(factor_metric)
  
  stars <- data.frame(factor_metric$GICS_SECTOR_NAME, stars)
  
  colnames(stars) <- c('GICS_SECTOR_NAME', factor_name)
  
  stars_sector[[i]] <- stars
}

stars_sector <- Reduce(function(x, y) merge(x, y, all=TRUE), stars_sector)

stars_sector <- stars_sector %>% 
  mutate(across(!GICS_SECTOR_NAME, ~strrep('\xE2\xAD\x90', .x))) %>%
  column_to_rownames(var = 'GICS_SECTOR_NAME')

datatable(stars_sector)
```

